export const stops = [
  {
    name: "56",
    completed: false,
    estimatedCompleteTime: "",
    completedTime: "",
    note: "two pickups",
    markers: {
      pickup: false,
      both: false,
      pallet: false,
    },
  },
  {
    name: "Flack",
    completed: false,
    estimatedCompleteTime: "",
    completedTime: "",
    note: "",
    markers: {
      pickup: true,
      both: false,
      pallet: false,
    },
  },
  {
    name: "gac",
    completed: false,
    estimatedCompleteTime: "",
    completedTime: "",
    note: "call",
    markers: {
      pickup: false,
      both: true,
      pallet: false,
    },
  },
  {
    name: "cameron",
    completed: false,
    estimatedCompleteTime: "",
    completedTime: "",
    note: "",
    markers: {
      pickup: false,
      both: false,
      pallet: true,
    },
  },
  {
    name: "mtt",
    completed: false,
    estimatedCompleteTime: "",
    completedTime: "",
    note: "",
    markers: {
      pickup: false,
      both: false,
      pallet: false,
    },
  },
  {
    name: "kca",
    completed: false,
    estimatedCompleteTime: "",
    completedTime: "",
    note: "",
    markers: {
      pickup: false,
      both: true,
      pallet: false,
    },
  },
  {
    name: "212",
    completed: false,
    estimatedCompleteTime: "",
    completedTime: "",
    note: "",
    markers: {
      pickup: false,
      both: true,
      pallet: true,
    },
  },
  {
    name: "171",
    completed: false,
    estimatedCompleteTime: "",
    completedTime: "",
    note: "",
    markers: {
      pickup: false,
      both: false,
      pallet: true,
    },
  },
  {
    name: "grieg",
    completed: false,
    estimatedCompleteTime: "",
    completedTime: "",
    note: "",
    markers: {
      pickup: true,
      both: false,
      pallet: false,
    },
  },
  {
    name: "B",
    completed: false,
    estimatedCompleteTime: "",
    completedTime: "",
    note: "",
    markers: {
      pickup: false,
      both: false,
      pallet: false,
    },
  },
  {
    name: "A",
    completed: false,
    estimatedCompleteTime: "",
    completedTime: "",
    note: "",
    markers: {
      pickup: false,
      both: false,
      pallet: false,
    },
  },
  {
    name: "W",
    completed: false,
    estimatedCompleteTime: "",
    completedTime: "",
    note: "",
    markers: {
      pickup: false,
      both: false,
      pallet: false,
    },
  },
  {
    name: "J",
    completed: false,
    estimatedCompleteTime: "",
    completedTime: "",
    note: "",
    markers: {
      pickup: false,
      both: false,
      pallet: false,
    },
  },
  {
    name: "SAR",
    completed: false,
    estimatedCompleteTime: "",
    completedTime: "",
    note: "",
    markers: {
      pickup: false,
      both: false,
      pallet: false,
    },
  },
  {
    name: "Modex",
    completed: false,
    estimatedCompleteTime: "",
    completedTime: "",
    note: "two pickups",
    markers: {
      pickup: false,
      both: false,
      pallet: false,
    },
  },
  {
    name: "Modex",
    completed: false,
    estimatedCompleteTime: "",
    completedTime: "",
    note: "two pickups",
    markers: {
      pickup: false,
      both: false,
      pallet: false,
    },
  },
  {
    name: "Modex",
    completed: false,
    estimatedCompleteTime: "",
    completedTime: "",
    note: "two pickups",
    markers: {
      pickup: false,
      both: false,
      pallet: false,
    },
  },
  {
    name: "Modex",
    completed: false,
    estimatedCompleteTime: "",
    completedTime: "",
    note: "two pickups",
    markers: {
      pickup: false,
      both: false,
      pallet: false,
    },
  },
  {
    name: "Modex",
    completed: false,
    estimatedCompleteTime: "",
    completedTime: "",
    note: "two pickups",
    markers: {
      pickup: false,
      both: false,
      pallet: false,
    },
  },
  {
    name: "Modex",
    completed: false,
    estimatedCompleteTime: "",
    completedTime: "",
    note: "two pickups",
    markers: {
      pickup: false,
      both: false,
      pallet: false,
    },
  },
  {
    name: "Modex",
    completed: false,
    estimatedCompleteTime: "",
    completedTime: "",
    note: "two pickups",
    markers: {
      pickup: false,
      both: false,
      pallet: false,
    },
  },
  {
    name: "Modex",
    completed: false,
    estimatedCompleteTime: "",
    completedTime: "",
    note: "two pickups",
    markers: {
      pickup: false,
      both: false,
      pallet: false,
    },
  },
  {
    name: "Modex",
    completed: false,
    estimatedCompleteTime: "",
    completedTime: "",
    note: "two pickups",
    markers: {
      pickup: false,
      both: false,
      pallet: false,
    },
  },
  {
    name: "Modex",
    completed: false,
    estimatedCompleteTime: "",
    completedTime: "",
    note: "two pickups",
    markers: {
      pickup: false,
      both: false,
      pallet: false,
    },
  },
  {
    name: "Modex",
    completed: false,
    estimatedCompleteTime: "",
    completedTime: "",
    note: "two pickups",
    markers: {
      pickup: false,
      both: false,
      pallet: false,
    },
  },
];
